### ISSUE TITLE
User team 1st sprint

### ISSUE THREAD

**Issue by vasopikof** [CCPX-system/CCPX-application#4]
1. Login 5%
2. register 10%

**Comment by zhuyf8899** [comment]
as well as some environment setting

**Comment by zhuyf8899** [comment]
龚长金 implements this but for some network problems 朱一凡 commit for him this time

**Comment by vasopikof** [comment]
Overdue for 1 day, please finish all the things in this sprint. If it was done, please close this issue.

@zhuyf8899

**Comment by zhuyf8899** [comment]
Login 5/5
register 10/10
