### ISSUE TITLE
UI team 1st sprint

### ISSUE THREAD

**Issue by vasopikof** [CCPX-system/CCPX-application#5]
1.create html pages for user interface part 1 (10%)

**Comment by FlorenceMei** [comment]
@quentinlegaux est-ce que tu vois ce message?

**Comment by quentinlegaux** [comment]
yes

**Comment by vasopikof** [comment]
Overdue for 1 day, please finish all the things in this sprint. If it was done, please close this issue.

@quentinlegaux

**Comment by FlorenceMei** [comment]
Status: working
Completed: 3/5

**Comment by FlorenceMei** [comment]
1) LOGIN:

Worker: Quentin
Status: done
Commit: 

2) REGISTER: 

Worker: Artem
Status: done
Commit:

3) MAINPAGE:

Worker: Helen
Status: working
Commit:

4) HOMEPAGE:

Worker: Luna
Status: done
Commit: 

5) RESET PASSWORD:

Worker: Sardor
Status: Working
Commit:
